name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files for debugging
        run: |
          echo "Root directory:"
          ls -la
          echo "Client dist directory:"
          ls -la client/dist/ || echo "client/dist not found"
          echo "Checking if files exist:"
          test -f client/dist/index.html && echo "✅ index.html exists" || echo "❌ index.html missing"
          test -d client/dist/assets && echo "✅ assets directory exists" || echo "❌ assets directory missing"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          exclude: |
            client/
            server/
            admin/
            scripts/
            .github/
            *.md
            *.js
            *.bat
            node_modules/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
